-- Global once-per-word cache of LLM-generated study materials for the weekly
-- digest (English-medium; replaces the dropped en_ko_translations pipeline).
-- Generated by the quiz edge function on cache miss; JSON-validated before
-- insert. Only the service role touches it: RLS enabled with NO policies.

create table public.word_study_materials (
  word text primary key,                  -- normalized (lowercase, trimmed)
  definition text not null,
  examples jsonb not null,                -- string[] (1-2 sentences)
  similar jsonb not null,                 -- [{phrase, nuance}] (2-3 entries)
  recognition_distractors jsonb not null, -- string[3] wrong definitions
  cloze jsonb not null,                   -- {sentence, distractors: string[3]}
  model text not null,
  generated_at timestamptz not null default now()
);

alter table public.word_study_materials enable row level security;
